[package]
name = "ldtk_topdown"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.10.1", features = ["dynamic_linking"] }
bevy_ecs_ldtk = "0.7.0"
bevy_rapier2d = "0.21.0"
big-brain = "0.17.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
